name: Autoflip Salient Crop

on:

  # push:
  #   branches:
  #     - master

  workflow_dispatch:

env:
  VIDEO_URL:            'https://londonparkour.com/wp-content/uploads/Essential/Epic-Slider/stranglers_min.mp4'
  # VIDEO_URL:          ${{ github.event.head_commit.message }}
  SERVER:               'londonparkour.com'
  GLOG_logtostderr:     '1'

jobs:

  build:


    runs-on: ubuntu-latest
    container:
      image: docker://londonparkour/autoflip:latest
      
    steps:

      # - name: My first step
      #   uses: docker://londonparkour/autoflip
      #   with:
      #     entrypoint: /bin/echo "hello"


      - name: download video from url
        run: |
            wget ${{ env.VIDEO_URL }} -O /video/video.mp4


      - name: run autoflip
        run: |
            cd /mediapipe
            /bin/sh -c "bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --calculator_graph_config_file=/mediapipe/${config} --input_side_packets=input_video_path=/video/${input_video},output_video_path=/video/${output_video},aspect_ratio=${aspect_ratio},key_frame_crop_viz_frames_path=/video/${points_output},salient_point_viz_frames_path=/video/${frames_output}" || true



      - name: Setup tools
        run: |
          apt-get update
          apt-get install -y ssh sshpass



      - name: Copy Video to Server
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{env.SERVER}} >> ~/.ssh/known_hosts
          ls -la /video
          sshpass -p '${{secrets.PASSWORD}}' scp StrictHostKeyChecking=no /video/video_crop.mp4 ${{secrets.USER}}@${{env.SERVER}}:/home/ios/videos
