name: Autoflip Salient Crop

on:

  # push:
  #   branches:
  #     - master

  # schedule:
  #   - cron:  '0 1 * * *'
    
  workflow_dispatch:

env:
  VIDEO_URL: ${{ github.event.head_commit.message }}
  SERVER:    'londonparkour.com'
  USER:      ${{secrets.USER}}
  PASSWORD:  ${{secrets.PASSWORD}}

jobs:

  build:
    runs-on: londonparkour/autoflip:latest

    steps:

      - uses: actions/checkout@v2

      - name: download video from url
        run: |
            wget -O /videos/video.mp4 ${{ env.VIDEO_URL }}


      - name: run autoflip
        run: |
            /bin/sh -c bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \
              --calculator_graph_config_file=${config} \
              --input_side_packets= input_video_path=/video/${input_video},output_video_path=/video/${output_video},aspect_ratio=${aspect_ratio},key_frame_crop_viz_frames_path=/video/${points_output},salient_point_viz_frames_path=/video/${frames_output}

      - name: Setup tools
        run: |
          apt-get update
          apt-get install -y rsync ssh


      # DEBUG with NGROK.
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
          NGROK_REGION: eu