name: Autoflip Salient Crop

on:

  # push:
  #   branches:
  #     - master

  workflow_dispatch:

env:
  VIDEO_URL:            'https://londonparkour.com/wp-content/uploads/Essential/Epic-Slider/stranglers_min.mp4'
  # VIDEO_URL:          ${{ github.event.head_commit.message }}
  SERVER:               'londonparkour.com'
  GLOG_logtostderr:     '1'

jobs:

  build:


    runs-on: ubuntu-latest
    container:
      image: docker://londonparkour/autoflip:latest
      
    steps:

      # - name: My first step
      #   uses: docker://londonparkour/autoflip
      #   with:
      #     entrypoint: /bin/echo "hello"


      - name: download video from url
        run: |
            wget ${{ env.VIDEO_URL }} -O /video/video.mp4


      - name: run autoflip
        run: |
            echo "CONFIG: ${config}"
            cd /mediapipe
            ls -la ./
            ls -la /mediapipe/mediapipe/examples/desktop/autoflip/

            /bin/sh -c "/mediapipe/bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \
              --calculator_graph_config_file=/mediapipe/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \
              --input_side_packets=input_video_path=/video/video.mp4, \
                  output_video_path=/video/video_crop.mp4, \
                  aspect_ratio=9:16, \
                  key_frame_crop_viz_frames_path=/video/video_points.mp4, \
                  salient_point_viz_frames_path=/video/video_frames.mp4" || true
            




      - name: Setup tools
        run: |
          apt-get update
          apt-get install -y rsync ssh sshpass



      - name: Copy Video to Server
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H londonparkour.com >> ~/.ssh/known_hosts
          sshpass -p '${{secrets.PASSWORD}}' scp /video/video_crop.mp4 ${{secrets.USER}}@${{env.SERVER}}:/home/ios/videos


      # # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu
