name: Autoflip Salient Crop

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                                                              │
# │                           You can run in two ways:                           │
# │                                                                              │
# │   1. With a Commit with the URL of the input video as the commit message.    │
# │                                                                              │
# │                           2. With a CURL request:                            │
# │                                    curl \                                    │
# │                                  -X POST \                                   │
# │                  -H "Accept: application/vnd.github+json" \                  │
# │                  -H "Authorization: Bearer GITHUB_PAT_KEY"\                  │
# │                   -H "X-GitHub-Api-Version: 2022-11-28" \                    │
# │        https://api.github.com/repos/ioroot/AI__autoflip/dispatches \         │
# │        -d '{"event_type":"run_autoflip","client_payload":{         \         │
# │           "VIDEO_URL":  "HTTP://VIDEOURL.COM/VIDEO.MP4",        \            │
# │                           "ASPECT_RATIO":"1:2"}}'                            │
# │                                                                              │
# │                                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────╯
on:

  # push:
  #   branches:
  #     - master

  # Manually via github button
  # workflow_dispatch:

  # Via a webhook
  repository_dispatch:
    types: run_autoflip

env:

  
  # ╭──────────────────────────────────────────────────────────╮
  # │                        Video URL                         │
  # │        1. Get Data from CURL request and webhook         │
  # │            2. or Get URL from commit message             │
  # ╰──────────────────────────────────────────────────────────╯
  VIDEO_URL:            ${{ github.event.client_payload.VIDEO_URL || github.event.head_commit.message }} 
  # VIDEO_URL:            'https://londonparkour.com/wp-content/uploads/Essential/Epic-Slider/stranglers_min.mp4'     # Hard coded

  # ╭──────────────────────────────────────────────────────────╮
  # │              Where to upload the result to.              │
  # │                      - Server name                       │
  # │                     - Target folder.                     │
  # ╰──────────────────────────────────────────────────────────╯
  SERVER:               'londonparkour.com'
  TARGET_ROOT_FOLDER:   '/var/www/vhosts/media.londonparkour.com/videos'

  # ╭──────────────────────────────────────────────────────────╮
  # │                Aspect Ratio to output as.                │
  # ╰──────────────────────────────────────────────────────────╯
  ASPECT_RATIO:         ${{ github.event.client_payload.ASPECT_RATIO }} 
  config:               'development'



jobs:

  build:


    runs-on: ubuntu-latest
    container:

      # Run the custom autoflip container.
      image: docker://londonparkour/autoflip:latest
      
    steps:

      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
      # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
      - name: Test the repository_dispatch fields
        run: |
          echo "VIDEO_URL: ${VIDEO_URL}"
          echo "ASPECT_RATIO: ${ASPECT_RATIO}"



      - name: download video from url
        run: |
            wget ${VIDEO_URL} -O /video/video.mp4
            mkdir -p /video/autoflip



      - name: run autoflip
        run: |
            cd /mediapipe
            /bin/sh -c "bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --calculator_graph_config_file=/mediapipe/${config} --input_side_packets=input_video_path=/video/${input_video},output_video_path=/video/autoflip/${output_video},aspect_ratio=${ASPECT_RATIO},key_frame_crop_viz_frames_path=/video/${points_output},salient_point_viz_frames_path=/video/${frames_output}" || true



      - name: Setup tools
        run: |
          apt-get update
          apt-get install -y rsync ssh sshpass



      - name: Copy Video to Server
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{env.SERVER}} >> ~/.ssh/known_hosts

          FOLDER_DATE=$(echo $VIDEO_URL | cut -d / -f5)
          FOLDER_CATEGORY=$(echo $VIDEO_URL | cut -d / -f6)

          SOURCE_DIR="/video/autoflip"
          TARGET_DIR="${TARGET_ROOT_FOLDER}/${FOLDER_DATE}/${FOLDER_CATEGORY}/"

          echo "SOURCE DIR: ${SOURCE_DIR}"
          echo "TARGET DIR: ${TARGET_DIR}"

          sshpass -p '${{secrets.PASSWORD}}' scp -v -p -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SOURCE_DIR} ${{secrets.USER}}@${{env.SERVER}}:${TARGET_DIR}
